# Generated by Django 4.0.6 on 2022-08-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=101)),
                ('lastname', models.CharField(max_length=101)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('gender', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('reg_date', models.DateTimeField()),
            ],
        ),
    ]
