# Generated by Django 4.0.6 on 2022-08-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_userregistrationform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistrationForm',
            new_name='user',
        ),
    ]
