# Generated by Django 4.0.6 on 2022-08-03 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_user_image_alter_user_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='user_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='members.members'),
            preserve_default=False,
        ),
    ]
