# Generated by Django 4.0.6 on 2022-08-08 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_user_image_alter_user_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='video',
            field=models.FileField(null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
