# Generated by Django 4.0.6 on 2022-08-08 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_movies_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='released_date',
        ),
        migrations.AlterField(
            model_name='movies',
            name='video',
            field=models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
