# Generated by Django 4.0.6 on 2022-08-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_movies_released_date_alter_movies_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(choices=[('action', 'ACTION'), ('comedy', 'COMEDY'), ('music', 'MUSIC')], max_length=255),
        ),
    ]
