# Generated by Django 4.0.6 on 2022-08-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_movies_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='url',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
